apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8svalidregistry
spec:
  crd:
    spec:
      names:
        kind: K8sValidRegistry
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            registry:
              type: string
          required:
            - registry          

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8svalidregistry

        violation[{"msg": msg, "details": {"registry": required_registry}}] {
          required_registry := input.parameters.registry
          some container
          input_containers[container]
          not startswith(container.image, required_registry)
          msg := sprintf("container image refers to illegal registry (must be %v)", [required_registry])
        }

        input_containers[container] {
          container := input.review.object.spec.containers[_]
        }

        input_containers[container] {
          container := input.review.object.spec.template.spec.containers[_]
        }
